# Generated by Django 2.0 on 2021-08-02 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.m_department', verbose_name='所属部署'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(blank=True, to='employee.m_skill', verbose_name='スキル'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='training',
            field=models.ManyToManyField(blank=True, to='employee.m_training', verbose_name='トレーニング'),
        ),
    ]
